export const CONFIG = {
    SCRIPT_ID: "ig-analyzer",
    SCRIPT_NAME: "Instagram Follower Analyzer",
    BACKUP_SCHEMA_VERSION: 1,
    STORAGE_KEY: "ig_snapshot_v2",
    POSITION_KEY: "ig_panel_position_v2",
    WHITELIST_KEY: "ig_whitelist_v2",
    HISTORY_KEY: "ig_history_v2",
    CHURN_KEY: "ig_churn_v3",
    DEACTIVATED_KEY: "ig_deactivated_v3",
    BLOCKED_KEY: "ig_blocked_v1",
    TOUR_KEY: "ig_tour_completed_v1",
    RENAMED_KEY: "ig_renamed_v1",
    STORY_ANOMALY_KEY: "ig_story_anomaly_v1",
    STORY_OBS_KEY: "ig_story_observations_v1",
    STORY_MIN_OBSERVATIONS: 3,
    STORY_MIN_ANOMALIES_FOR_FLAG: 2,
    STORY_STREAK_FOR_MEDIUM_CONFIDENCE: 2,
    FOLLOWING_HASH: "d04b0a864b4b54837c0d870b0e77e076",
    FOLLOWERS_HASH: "c76146de99bb02f6415203be841dd25a",
    PAGE_SIZE: 50,
    BASE_RATE_LIMIT_MS: 1500, 
    MAX_RETRIES: 4,           
    DEBUG: false,
    MIN_VISIBLE_PX: 50,
    DEFAULT_POSITION: { top: 80, right: 20 }
};